name = "Navier_Stokes_Spectral_Method"
version = "0.1.0"
license = "MIT"
author = "Jules Minard"
maintainer = "minard.jules@yahoo.com"
copyright = "Copyright 2023-2025, Jules Minard"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false


[install]
library = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[preprocess]
cpp.directories = ["src/IO_Module.f90"]
# cpp.macros=["_WIN32"]
# cpp.macros=["_UNIX"]

[dependencies]
gtk-fortran = { git = "https://github.com/vmagnin/gtk-fortran.git", rev = "v4.6.0" }
NAFPack = {git = "https://github.com/Minard-Jules/NAFPack.git"}
openmp = "*"
